# Generated by Django 5.0.6 on 2024-07-12 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_group_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='groups',
            options={'verbose_name_plural': 'Groups'},
        ),
    ]
