# Generated by Django 5.0.6 on 2024-07-19 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_comment_file_alter_productattribute_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='attribute_name',
            new_name='attribute',
        ),
    ]
