# Generated by Django 5.0.6 on 2024-07-12 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_category_options_alter_groups_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
