# Generated by Django 5.0.6 on 2024-07-22 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_productattribute_attribute_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='attribute',
            new_name='attribute_name',
        ),
        migrations.RenameField(
            model_name='productattribute',
            old_name='attribute',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='productattribute',
            old_name='attribute_value',
            new_name='value',
        ),
    ]
