# Generated by Django 5.0.6 on 2024-07-31 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_author_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
